# 파이썬 프로그래밍 : Numpy 실습

## 배열 생성하기

In [2]:
import numpy as np

In [5]:
data1 = range(6)
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [8]:
a1[2]

2

In [9]:
data2 = [0.1, 5.0, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [10]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [17]:
a.shape # (행, 열)

(3,)

In [18]:
a.ndim # 배열의 차수

1

In [19]:
a.dtype # 데이터 타입

dtype('int32')

In [22]:
a.itemsize

4

In [21]:
a.size # 항목의 개수

3

In [25]:
a1 = np.array(range(6))
a1.dtype

dtype('int32')

In [29]:
a2 = np.array([0.1, 5, 4, 12, 0.7])
a2.dtype

dtype('float64')