# 파이썬 Numpy 실습

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
np.zeros(10) # 값이 0인 1차원 배열

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3, 4)) # 값이 0인 2차원 배열

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(5) # 값이 1인 1차원 배열

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3, 4)) # 값이 1인 2차원 배열

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
str_a1

array(['1.567', '0.123', '5.123', '9', '8'], dtype='<U5')

In [22]:
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [23]:
str_a2 = np.array(['1', '2', '3', '4'])
str_a2

array(['1', '2', '3', '4'], dtype='<U1')

In [25]:
num_a2 = str_a2.astype(int)
num_a2

array([1, 2, 3, 4])

In [26]:
np.random.rand()

0.9061841610278817