# 배열 데이터를 효과적으로 다루는 NumPy

## 1. 배열 생성하기

### NumPy 패키지 임포트

In [5]:
import numpy as np

### 시퀀스 데이터로부터 배열 생성

In [2]:
arr_obj = np.array(seq_data)

NameError: name 'seq_data' is not defined

### 리스트로부터NumPy의1차원배열을생성하는예

In [5]:
import numpy as np 
data1 = [0, 1, 2, 3, 4, 5] 
a1 = np.array(data1) 
a1

array([0, 1, 2, 3, 4, 5])

### 정수와 실수가 혼합된 리스트 데이터로 NumPy 배열을 만들어 보자

In [6]:
data2 = [0.1,  5,  4,  12,  0.5] 
a2 = np.array(data2) 
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

## 2. 배열의 객체 타입 확인

In [8]:
import numpy as np 
a1 = np.array([0, 1, 2, 3, 4, 5])
a1.dtype 

dtype('int32')

In [9]:
import numpy as np 
a2 = np.array([0.1, 5, 4, 12, 0.5])
a2.dtype

dtype('float64')

## 3. 다차원 배열 생성

In [10]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 4. 범위를 지정해 배열 생성

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

## 5. m x n 행렬 : .reshape(m, n)

In [16]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
b1 = np.arange(12).reshape(4,3) 
b1.shape

(4, 3)

In [18]:
b2 = np.arange(5) 
b2.shape

(5,)

## 6. 범위의 시작과 끝, 데이터의 개수를 지정해 배열 생성 : .linspace()

In [20]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

## 7. 특별한 형태의 배열 생성

In [22]:
np.zeros(10) # 10개의 원소가 모두 0을 갖는 1차원 배열 생성

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,4)) # 모든 원소가 0인 3 x 4의 2차원 배열을 생성

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones(5) # 5개의 원소가 모두 1을 갖는 1차원 배열 생성

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((3,5)) # 모든 원소가 1인 3 x 5의 2차원 배열을 생성

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 8. 단위 행렬 생성 : eye(n)

In [26]:
np.eye(3) # 3 x 3의 단위 행렬을 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 9. 배열의 데이터 타입 변환

In [27]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

## 10. NumPy 배열의데이터 타입변환 : astype()

### 실수 형태의 문자열을 원소로 갖는 NumPy 배열을 실수 타입으로 변환하는 예

In [28]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8']) 
num_a1 = str_a1.astype(float) 
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [29]:
str_a1.dtype # str_a1은 dtype이 유니코드(U)이며 문자수는 최대 5개

dtype('<U5')

In [30]:
num_a1.dtype # num_a1은 dtype이 실수(float)

dtype('float64')

### 정수 형태의 문자열을 원소로 갖는 NumPy 배열을 정수로 변환하는 예

In [31]:
str_a2 = np.array(['1', '3', '5', '7', '9']) 
num_a2 = str_a2.astype(int) 
num_a2

array([1, 3, 5, 7, 9])

In [32]:
str_a2.dtype # str_a2는 dtype이 유니코드(U)이며 문자수는 최대 1개

dtype('<U1')

In [33]:
num_a2.dtype # num_a2는 dtype이 정수(int32)

dtype('int32')

### 실수를 원소로 갖는 NumPy 배열을 정수로 변환하는 예

In [34]:
num_f1 = np.array([10,  21,  0.549,  4.75,  5.98]) 
num_i1 = num_f1.astype(int) 
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [35]:
num_f1.dtype # num_f1은 dtype이 실수(float64)

dtype('float64')

In [36]:
num_i1.dtype # num_i1은 dtype이 정수(int32)

dtype('int32')

## 11. 실수 난수 배열의 생성 : random.rand()

In [37]:
np.random.rand()

0.11192820316532315

In [38]:
np.random.rand(2,3)

array([[0.29911356, 0.31851051, 0.85765746],
       [0.41431878, 0.11618131, 0.84109502]])

## 12. 정수 난수 배열의 생성 : random.randint()

In [39]:
np.random.randint(10, size=(3, 4))

array([[8, 7, 6, 7],
       [9, 3, 0, 5],
       [8, 9, 7, 6]])

In [40]:
np.random.randint(1, 30)

24

## 13. 배열의 연산 - 기본 연산

In [41]:
arr1 = np.array([10, 20, 30, 40]) # 배열의 형태가 같은 두 개의 1차원 배열을 생성한다. 
arr2 = np.array([1, 2, 3, 4]) # 즉, 두 배열의 'ndarray.shape'의 결과가 같음을 의미한다. 

In [42]:
arr1 + arr2 # 두 배열의 합

array([11, 22, 33, 44])

In [43]:
arr1 - arr2 # 두 배열의 차

array([ 9, 18, 27, 36])

In [44]:
arr2 * 2 # 배열에 상수를 곱한다. 

array([2, 4, 6, 8])

In [45]:
arr2 ** 2 # 배열의 거듭 제곱

array([ 1,  4,  9, 16])

In [46]:
arr1 * arr2 # 두 배열의 곱

array([ 10,  40,  90, 160])

In [47]:
arr1 / arr2 # 두 배열의 나눗셈

array([10., 10., 10., 10.])

In [48]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [49]:
arr1 > 20

array([False, False,  True,  True])

## 14. 통계를 위한 연산

In [50]:
arr3 = np.arange(5) 
arr3

array([0, 1, 2, 3, 4])

In [51]:
[arr3.sum(), arr3.mean()] # 배열의 합과 평균을 구한다. 

[10, 2.0]

In [52]:
[arr3.std(), arr3.var()] # 배열의 표준 편차와 분산을 구한다. 

[1.4142135623730951, 2.0]

In [53]:
[arr3.min(), arr3.max()] # 배열의 최소값과 최대값을 구한다. 

[0, 4]

### arr4를 이용해 누적합(cumsum())과 누적곱(cumprod())을 구해보자. 

In [54]:
arr4 = np.arange(1,5) 
arr4

array([1, 2, 3, 4])

In [56]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [57]:
arr4.cumprod()

array([ 1,  2,  6, 24])

## 15. 행열 연산

In [59]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [60]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

### 행렬 A와 B의 곱(A * B)

In [61]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [62]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

### 행렬 A의 전치 행렬

In [63]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [64]:
A.transpose()

array([[0, 2],
       [1, 3]])

### 행렬 A의 역행렬

In [65]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

### 행렬 A의 행렬식

In [66]:
np.linalg.det(A)

-2.0

## 16. 배열의 인덱싱

In [6]:
a1 = np.array([0, 10, 20, 30, 40, 50]) # 1차원 배열 생성
a1

array([ 0, 10, 20, 30, 40, 50])

In [68]:
a1[0] # 배열(a1)에서 위치 0의 원소 

0

In [69]:
a1[4] # 배열(a1)에서 위치 4의 원소 선택

40

In [70]:
a1[5] = 70 
a1

array([ 0, 10, 20, 30, 40, 70])

In [8]:
a1[[1,3,4]] # 1차원 배열 a1에서 1, 3, 4의 위치에 있는 원소 10, 30, 40을 가져온다

array([10, 30, 40])

In [11]:
a2 = np.arange(10, 100, 10).reshape(3,3) # 2차원 배열 a2에서 0행 2열의 원소를 선택해서 가져온다. 
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [73]:
a2[2, 2] = 95 # 2차원 배열 a2에서 행과 열의 위치를 지정해서 원소의 값을 변경할 수 있다. 
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

### 다음은 특정 행을 지정해 행 전체의 값을 변경하는 예

In [74]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [75]:
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

### 2차원 배열의 여러 원소를 선택

In [76]:
a2[[0, 2], [0, 1]] # 2차원 배열 a2에서 (0, 0) 위치의 원소 10과 (2, 1) 위치의 원소 80을 선택해서 가져온다. 

array([10, 80])

### 배열에 조건을 지정해 조건에 맞는 배열을 선택

In [77]:
a = np.array([1, 2, 3, 4, 5, 6]) # 배열 a에서 a > 3 조건을 만족하는 원소만 가져온다. 
a[a > 3]

array([4, 5, 6])

In [80]:
a[(a % 2) == 0] # 조건을 이용해서 배열 a에서 짝수인 원소만 선택하는 예

array([2, 4, 6])

## 17. 배열의 슬라이싱

In [81]:
b1 = np.array([0, 10, 20, 30, 40, 50]) # 1차원 배열 b1에서 1 ~ 3의 배열 원소를 슬라이싱
b1[1:4]

array([10, 20, 30])

In [82]:
b1[:3]

array([ 0, 10, 20])

In [83]:
b1[2:]

array([20, 30, 40, 50])

In [84]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [85]:
b1[3:6] = 60 # 여러 원소의 값을 같은 값으로 변경하려면 하나의 값을 지정해 변경할 수 있다.
b1

array([ 0, 10, 25, 60, 60, 60])

### 2차원 배열의 슬라이싱을 위해 2차원 배열을 생성하자. 

In [86]:
b2 = np.arange(10, 100, 10).reshape(3,3) 
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [87]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [88]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

### 2차원 배열에서 행을 지정하고 열을 슬라이싱하는 예

In [90]:
b2[1][0:2]

array([40, 50])

In [91]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])